### ISSUE TITLE
Separate example project from library repo

### ISSUE THREAD

**Issue by wjmelements** [uport-project/UPTEthereumSigner#3]

**Comment by joshuabell** [comment]
Sounds good, will do!

This project was formerly going in the Cocoapod direction. Cocoapods has out of the box functionality to support both the Cocoapod source files and an example project cleanly in one repo. Since the install direction is now submodules it doesn't make sense anymore to put the example project in the same repo. It also makes sense to move the example project to it's own repo for separation of concerns reasons!

**Comment by joshuabell** [comment]
removed blocker because @wjmelements configured and released the CoreEthereum pod that solves the issues with the original CoreBitcoin project being either available to run on the simulator or iOS devices but not both!

**Comment by joshuabell** [comment]
Done: https://github.com/uport-project/UPTEthereumSigner-Example
